server:
  port: 8761
eureka:
  instance:
    hostname: 111.231.64.142
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
